### ISSUE TITLE
get list of ID's 

### ISSUE THREAD

**Issue by toninog** [kleiram/transmission-php#48]
Hi

Is there a way to get a list of the active torrents ?  I can see the 
$torrents = $transmission->all();

but how do you get the id's from that ?

Thanks

**Comment by kleiram** [comment]
Hi there! The `Transmission::all` method returns an array of [`Transmission\Model\Torrent`](https://github.com/kleiram/transmission-php/blob/master/lib/Transmission/Model/Torrent.php) objects.  This model has a `Torrent::getId()` method to retrieve the identifier of the torrent. So for example, you could do:

```php
foreach ($transmission->all() as $torrent) {
    $id = $torrent->getId();
}
```

I think you should be careful with using the torrents though, since they seem to change when Transmission restarts (could be wrong though!).

**Comment by toninog** [comment]
Perfect thanks.

**Comment by kleiram** [comment]
You're welcome!
